# Site settings
title: Sustainable Soft Robotic Fabrication
email: christine [dot] braganza [at] bristol.ac.uk
url: https://cbraganz.github.io
description: "Find out more about materials, fabrication methods and resources below!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#f57607'

# Footer settings
footer: SustainableSoftRoboticFabrication

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/christine-braganza000

# Build settings
markdown: kramdown
permalink: pretty
