# Site settings
title: Sustainable Soft Robotic Fabrication
email: christine.braganza@bristol.ac.uk
url: https://cbraganz.github.io
description: "Find out more about !!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: RicePaperRapidFabrication

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/christine-braganza000

# Build settings
markdown: kramdown
permalink: pretty
